export const Details = [
  {
    house_id: "1",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg",
    detail_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2022/Aug/15/Photo_h300_w450/62626313_5_WhatsApp-Image-2022-08-15-at-3-08-37-PM_300_450.jpg",
    house_name: "Nest Craft",
    description: "Nest Builders",
    limit: "Marketed by Bhaggyam Constructions Pvt",
    space: "3 BHK Flats",
    flat: "2",
    Bhk: "3 BHK",
    house_price: "₹ 39.53 Lac",
    Loan: "Get ₹9,000 cashback on Home Loan",
    marketing_company: "Nest Builder",
    owner_name: "Josh singh",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Sithalapakkam",
    super_area: "1055sqft",
    under_construction: "5/22/2022",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "500sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "2",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg",
    detail_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/20/Photo_h180_w240/65862089_17_hoto2_180_240.jpg",
    house_name: "Pearl Queens Park",
    description: "Pearl Constructions",
    limit: "Marketed by Pearl Constructions Pvt",
    space: "2 BHK Flats",
    flat: "2",
    Bhk: "2 BHK",
    house_price: "₹ 43.6 Lac",
    Loan: "Get ₹11,096 cashback on Home Loan",
    marketing_company: "Pearl Builder",
    owner_name: "singh",
    val: "Real value",
    house_address: "Owner 2 BHK Flat for Sale in Perfect Residency",
    house_area: "Siruseri, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "3",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00813495/featureproject-img.jpg",
    detail_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/25/Photo_h180_w240/65861599_4_concia4_180_240.jpg",
    house_name: "Tulive Azpire",
    description: "Tulive GK Shetty",
    limit: "Marketed by Tulive GK Shetty",
    space: "1 BHK Flats",
    flat: "2",
    Bhk: "1 BHK",
    house_price: "₹ 13.6 Lac",
    Loan: "Get ₹1,096 cashback on Home Loan",
    marketing_company: "Tulive Builder",
    owner_name: "Roshan",
    val: "Real value",
    house_address: "Owner 1 BHK Flat for Sale in Perfect Residency",
    house_area: "Adyar,Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "4",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00816805/featureproject-img.jpg",
    detail_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/25/Photo_h180_w240/65861599_4_concia4_180_240.jpg",
    house_name: "Vtech Arputha",
    description: "Vtech Builders",
    limit: "Marketed by Vtech Builder Pvt Ltd",
    space: "3 BHK Flats",
    flat: "2",
    Bhk: "3 BHK",
    house_price: "₹ 48.4 Lac",
    Loan: "Get ₹10,096 cashback on Home Loan",
    marketing_company: "Vtech Builder",
    owner_name: "Kannan",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Ottiambakkam, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "700sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/17/2020",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 1200 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "2",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg",
    detail_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/20/Photo_h180_w240/65862089_17_hoto2_180_240.jpg",
    house_name: "Pearl Queens Park",
    description: "Pearl Constructions",
    limit: "Marketed by Pearl Constructions Pvt",
    space: "2 BHK Flats",
    flat: "2",
    Bhk: "2 BHK",
    house_price: "₹ 43.6 Lac",
    Loan: "Get ₹11,096 cashback on Home Loan",
    marketing_company: "Pearl Builder",
    owner_name: "singh",
    val: "Real value",
    house_address: "Owner 2 BHK Flat for Sale in Perfect Residency",
    house_area: "Siruseri, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "1",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg",
    detail_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2022/Aug/15/Photo_h300_w450/62626313_5_WhatsApp-Image-2022-08-15-at-3-08-37-PM_300_450.jpg",
    house_name: "Nest Craft",
    description: "Nest Builders",
    limit: "Marketed by Bhaggyam Constructions Pvt",
    space: "3 BHK Flats",
    flat: "2",
    Bhk: "3 BHK",
    house_price: "₹ 39.53 Lac",
    Loan: "Get ₹9,000 cashback on Home Loan",
    marketing_company: "Nest Builder",
    owner_name: "Josh singh",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Sithalapakkam",
    super_area: "1055sqft",
    under_construction: "5/22/2022",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "500sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "7",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/29/Photo_h300_w450/66819775_1_hatsAppImage20230412at12.24.33PM_300_450.jpeg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/29/Photo_h300_w450/66819775_5_hatsAppImage20230412at12.24.31PM2_300_450.jpeg",
    house_name: "Nest Craft",
    description: "Nest Builders",
    limit: "Marketed by Bhaggyam Constructions Pvt",
    space: "3 BHK Flats",
    flat: "2",
    Bhk: "3 BHK",
    house_price: "₹ 62.10 Lac",
    Loan: "Get ₹8,000 cashback on Home Loan",
    marketing_company: "Nest Builder",
    owner_name: "Raj Kannan",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Sithalapakkam",
    super_area: "1055sqft",
    under_construction: "5/22/2022",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "500sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 500 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "8",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/29/Photo_h0_w320/66819775_2_hatsAppImage20230412at12.24.31PM_0_320.jpeg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2022/Sep/01/Photo_h0_w320/62913389_4_0d136d5-867b-4cc9-b00a-a73fb682d6c6_0_320.jpg",
    house_name: "Pearl Queens Park",
    description: "Pearl Constructions",
    limit: "Marketed by Pearl Constructions Pvt",
    space: "2 BHK Flats",
    flat: "2",
    Bhk: "2 BHK",
    house_price: "₹ 50.6 Lac",
    Loan: "Get ₹11,096 cashback on Home Loan",
    marketing_company: "Pearl Builder",
    owner_name: "singh",
    val: "Real value",
    house_address: "Owner 2 BHK Flat for Sale in Perfect Residency",
    house_area: "Siruseri, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "9",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00813495/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2022/Dec/19/Photo_h0_w320/64720099-Image-3_0_320.jpg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2022/Dec/19/Photo_h300_w450/64720099-Image-2_300_450.jpg",
    house_name: "Tulive Azpire",
    description: "Tulive GK Shetty",
    limit: "Marketed by Tulive GK Shetty",
    space: "1 BHK Flats",
    flat: "2",
    Bhk: "1 BHK",
    house_price: "₹ 15.8 Lac",
    Loan: "Get ₹1,096 cashback on Home Loan",
    marketing_company: "Tulive Builder",
    owner_name: "Roshan",
    val: "Real value",
    house_address: "Owner 1 BHK Flat for Sale in Perfect Residency",
    house_area: "Adyar,Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "10",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00816805/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Jan/17/Photo_h0_w320/64577483_15_PropertyImage809-2716736210347_0_320.jpg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Jan/17/Photo_h300_w450/64577483_13_PropertyImage347-7593729262901_300_450.jpg",
    house_name: "Vtech Arputha",
    description: "Vtech Builders",
    limit: "Marketed by Vtech Builder Pvt Ltd",
    space: "3 BHK Flats",
    flat: "2",
    Bhk: "3 BHK",
    house_price: "₹ 28.4 Lac",
    Loan: "Get ₹3,096 cashback on Home Loan",
    marketing_company: "Vtech Builder",
    owner_name: "Kannan",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Ottiambakkam, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "700sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/17/2020",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 1200 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "11",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbimages/project/Photo_h0_w320/2022/02/23/Project-Photo-4-Annanagar-East-Chennai-5198361_1125_2000_0_320.jpg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Jun/03/Photo_h300_w450/66548113_2_WhatsApp-Image-2023-03-30-at-8-51-44-PM--1-_300_450.jpeg",
    house_name: "Pearl Queens Park",
    description: "Pearl Constructions",
    limit: "Marketed by Pearl Constructions Pvt",
    space: "2 BHK Flats",
    flat: "2",
    Bhk: "2 BHK",
    house_price: "₹ 14.6 Lac",
    Loan: "Get ₹2,096 cashback on Home Loan",
    marketing_company: "Pearl Builder",
    owner_name: "singh",
    val: "Real value",
    house_address: "Owner 2 BHK Flat for Sale in Perfect Residency",
    house_area: "Siruseri, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "12",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbimages/project/Photo_h0_w320/2022/02/23/Project-Photo-4-Annanagar-East-Chennai-5198361_1125_2000_0_320.jpg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Jan/17/Photo_h0_w320/64577483_3_IMG-20220419-WA0004_0_320.jpeg",
    house_name: "Nest Craft",
    description: "Nest Builders",
    limit: "Marketed by Bhaggyam Constructions Pvt",
    space: "3 BHK Flats",
    flat: "2",
    Bhk: "3 BHK",
    house_price: "₹ 32.53 Lac",
    Loan: "Get ₹7,000 cashback on Home Loan",
    marketing_company: "Nest Builder",
    owner_name: "Josh singh",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Sithalapakkam",
    super_area: "1055sqft",
    under_construction: "5/22/2022",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "500sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "13",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbphoto/locality/cropped_images/2020/Sep/18/Photo_h0_w320/79473_IMG-20200118-WA0007---sundar-s_0_320.jpg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2022/Nov/04/Photo_h300_w450/63977545_3_hatsAppImage2022-10-17at4.00.14PM_300_450.jpeg",
    house_name: "Nest Craft",
    description: "Nest Builders",
    limit: "Marketed by Bhaggyam Constructions Pvt",
    space: "2 BHK Flats",
    flat: "2",
    Bhk: "2 BHK",
    house_price: "₹ 19.53 Lac",
    Loan: "Get ₹2,000 cashback on Home Loan",
    marketing_company: "Nest Builder",
    owner_name: "Josh singh",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Sithalapakkam",
    super_area: "1055sqft",
    under_construction: "5/22/2022",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "500sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "14",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbphoto/locality/cropped_images/2022/Jan/25/Photo_h0_w320/63940_Overview_WuG9U9_0_320.jpg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2021/Aug/04/Photo_h300_w450/56281911_2_MG_4491_KanathurA_300_450.jpg",
    house_name: "Pearl Queens Park",
    description: "Pearl Constructions",
    limit: "Marketed by Pearl Constructions Pvt",
    space: "2 BHK Flats",
    flat: "2",
    Bhk: "2 BHK",
    house_price: "₹ 44.6 Lac",
    Loan: "Get ₹11,096 cashback on Home Loan",
    marketing_company: "Pearl Builder",
    owner_name: "singh",
    val: "Real value",
    house_address: "Owner 2 BHK Flat for Sale in Perfect Residency",
    house_area: "Siruseri, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "15",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00813495/featureproject-img.jpg",
    detail_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/25/Photo_h180_w240/65861599_4_concia4_180_240.jpg",
    house_name: "Tulive Azpire",
    description: "Tulive GK Shetty",
    limit: "Marketed by Tulive GK Shetty",
    space: "1 BHK Flats",
    flat: "2",
    Bhk: "1 BHK",
    house_price: "₹ 17.6 Lac",
    Loan: "Get ₹2,096 cashback on Home Loan",
    marketing_company: "Tulive Builder",
    owner_name: "Roshan",
    val: "Real value",
    house_address: "Owner 1 BHK Flat for Sale in Perfect Residency",
    house_area: "Adyar,Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "16",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00816805/featureproject-img.jpg",
    detail_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/25/Photo_h180_w240/65861599_4_concia4_180_240.jpg",
    house_name: "Vtech Arputha",
    description: "Vtech Builders",
    limit: "Marketed by Vtech Builder Pvt Ltd",
    space: "3 BHK Flats",
    flat: "2",
    Bhk: "3 BHK",
    house_price: "₹ 26.4 Lac",
    Loan: "Get ₹10,096 cashback on Home Loan",
    marketing_company: "Vtech Builder",
    owner_name: "Kannan",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Ottiambakkam, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "700sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/17/2020",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 1200 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "16",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg",
    detail_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/20/Photo_h180_w240/65862089_17_hoto2_180_240.jpg",
    house_name: "Pearl Queens Park",
    description: "Pearl Constructions",
    limit: "Marketed by Pearl Constructions Pvt",
    space: "2 BHK Flats",
    flat: "2",
    Bhk: "2 BHK",
    house_price: "₹ 40.6 Lac",
    Loan: "Get ₹11,096 cashback on Home Loan",
    marketing_company: "Pearl Builder",
    owner_name: "singh",
    val: "Real value",
    house_address: "Owner 2 BHK Flat for Sale in Perfect Residency",
    house_area: "Siruseri, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "17",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg",
    detail_img:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdNupqYLQqiaixZSJf-ws0n165j0EhXFkV7fka0T965Q&usqp=CAU&ec=48665699",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2022/Aug/15/Photo_h300_w450/62626313_5_WhatsApp-Image-2022-08-15-at-3-08-37-PM_300_450.jpg",
    house_name: "Nest Craft",
    description: "Nest Builders",
    limit: "Marketed by Bhaggyam Constructions Pvt",
    space: "3 BHK Flats",
    flat: "2",
    Bhk: "3 BHK",
    house_price: "₹ 20.53 Lac",
    Loan: "Get ₹2,000 cashback on Home Loan",
    marketing_company: "Nest Builder",
    owner_name: "Josh singh",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Sithalapakkam",
    super_area: "1055sqft",
    under_construction: "5/22/2022",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "500sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "18",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/29/Photo_h300_w450/66819775_1_hatsAppImage20230412at12.24.33PM_300_450.jpeg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/29/Photo_h300_w450/66819775_5_hatsAppImage20230412at12.24.31PM2_300_450.jpeg",
    house_name: "Nest Craft",
    description: "Nest Builders",
    limit: "Marketed by Bhaggyam Constructions Pvt",
    space: "3 BHK Flats",
    flat: "2",
    Bhk: "3 BHK",
    house_price: "₹ 17.10 Lac",
    Loan: "Get ₹2,000 cashback on Home Loan",
    marketing_company: "Nest Builder",
    owner_name: "Raj Kannan",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Sithalapakkam",
    super_area: "1055sqft",
    under_construction: "5/22/2022",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "500sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 500 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "19",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Apr/29/Photo_h0_w320/66819775_2_hatsAppImage20230412at12.24.31PM_0_320.jpeg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2022/Sep/01/Photo_h0_w320/62913389_4_0d136d5-867b-4cc9-b00a-a73fb682d6c6_0_320.jpg",
    house_name: "Pearl Queens Park",
    description: "Pearl Constructions",
    limit: "Marketed by Pearl Constructions Pvt",
    space: "2 BHK Flats",
    flat: "2",
    Bhk: "2 BHK",
    house_price: "₹ 55.6 Lac",
    Loan: "Get ₹17,096 cashback on Home Loan",
    marketing_company: "Pearl Builder",
    owner_name: "singh",
    val: "Real value",
    house_address: "Owner 2 BHK Flat for Sale in Perfect Residency",
    house_area: "Siruseri, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "20",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00813495/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2022/Dec/19/Photo_h0_w320/64720099-Image-3_0_320.jpg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2022/Dec/19/Photo_h300_w450/64720099-Image-2_300_450.jpg",
    house_name: "Tulive Azpire",
    description: "Tulive GK Shetty",
    limit: "Marketed by Tulive GK Shetty",
    space: "1 BHK Flats",
    flat: "2",
    Bhk: "1 BHK",
    house_price: "₹ 18.8 Lac",
    Loan: "Get ₹1,096 cashback on Home Loan",
    marketing_company: "Tulive Builder",
    owner_name: "Roshan",
    val: "Real value",
    house_address: "Owner 1 BHK Flat for Sale in Perfect Residency",
    house_area: "Adyar,Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "21",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00816805/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Jan/17/Photo_h0_w320/64577483_15_PropertyImage809-2716736210347_0_320.jpg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Jan/17/Photo_h300_w450/64577483_13_PropertyImage347-7593729262901_300_450.jpg",
    house_name: "Vtech Arputha",
    description: "Vtech Builders",
    limit: "Marketed by Vtech Builder Pvt Ltd",
    space: "3 BHK Flats",
    flat: "2",
    Bhk: "3 BHK",
    house_price: "₹ 22.4 Lac",
    Loan: "Get ₹3,096 cashback on Home Loan",
    marketing_company: "Vtech Builder",
    owner_name: "Kannan",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Ottiambakkam, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "700sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/17/2020",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 1200 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "22",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00776087/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbimages/project/Photo_h0_w320/2022/02/23/Project-Photo-4-Annanagar-East-Chennai-5198361_1125_2000_0_320.jpg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Jun/03/Photo_h300_w450/66548113_2_WhatsApp-Image-2023-03-30-at-8-51-44-PM--1-_300_450.jpeg",
    house_name: "Pearl Queens Park",
    description: "Pearl Constructions",
    limit: "Marketed by Pearl Constructions Pvt",
    space: "2 BHK Flats",
    flat: "2",
    Bhk: "2 BHK",
    house_price: "₹ 16.6 Lac",
    Loan: "Get ₹2,096 cashback on Home Loan",
    marketing_company: "Pearl Builder",
    owner_name: "singh",
    val: "Real value",
    house_address: "Owner 2 BHK Flat for Sale in Perfect Residency",
    house_area: "Siruseri, Chennai",
    super_area: "1055sqft",
    under_construction: "6/11/2021",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "600sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
  {
    house_id: "23",
    house_img:
      "https://cdn.staticmb.com/property/microsite/mb-banners/00773482/featureproject-img.jpg",
    detail_img:
      "https://img.staticmb.com/mbimages/project/Photo_h0_w320/2022/02/23/Project-Photo-4-Annanagar-East-Chennai-5198361_1125_2000_0_320.jpg",
    list_img:
      "https://img.staticmb.com/mbphoto/property/cropped_images/2023/Jan/17/Photo_h0_w320/64577483_3_IMG-20220419-WA0004_0_320.jpeg",
    house_name: "Nest Craft",
    description: "Nest Builders",
    limit: "Marketed by Bhaggyam Constructions Pvt",
    space: "3 BHK Flats",
    flat: "2",
    Bhk: "3 BHK",
    house_price: "₹ 36.53 Lac",
    Loan: "Get ₹7,000 cashback on Home Loan",
    marketing_company: "Nest Builder",
    owner_name: "Josh singh",
    val: "Real value",
    house_address: "Owner 3 BHK Flat for Sale in Perfect Residency",
    house_area: "Sithalapakkam",
    super_area: "1055sqft",
    under_construction: "5/22/2022",
    Beds: "2Beds",
    Baths: "2Baths",
    Balcony: "1Balcony",
    CarpetArea: "500sqft",
    Covered: "1Covered Parking",
    Tenant:"Bachelors/Family",
    under_construction: "8/7/2022",
    transaction: "Resale",
    furnishing: "Unfurnishing",
    features:
      "The apartment features a unique design with large open plan layouts and dual access",
    sqft_amount: "₹ 400 sqft",
    Facing: "North-East",
    TypeOfOwnership: "Freehold",
    car_parking: "",
    bathroom: "3",
    floor: "1 out of 3",
    lift: "1",
    status: "Ready to Move",
    Offer: "18 Months No Pre EMI",
    update: "Last contact made 2 days ago",
    bookingAmount: "₹50,000",
    rera_id: "TN/01/Building/0131/2017",
    flooring: "Vetrified",
    water_availability: "24 Hours Available",
    resident: "Flat",
  },
];
